In [1]:
import numpy as np

import pandas as pd

student_data = [
    [100, 80, 10],
    [90, 70, 7],
    [120, 100, 14],
    [80, 50, 2],
]

pd.DataFrame(student_data, columns=['iq', 'marks', 'package'])

    iq  marks  package
0  100     80       10
1   90     70        7
2  120    100       14
3   80     50        2

In [2]:
# using dict
student_dict = {
    'name': ['Ali', 'Saim', 'Haris', 'Usama', 'Hassan', 'Afzal'],
    'iq': [100, 90, 100, 50, 0, 0],
    'marks': [80, 70, 100, 50, 0, 0],
    'package': [10, 7, 14, 2, 0, 0]
}

students = pd.DataFrame(student_dict)
copyx = students.set_index('name')
print(copyx)

         iq  marks  package
name
Ali     100     80       10
Saim     90     70        7
Haris   100    100       14
Usama    50     50        2
Hassan    0      0        0
Afzal     0      0        0

In [3]:
df = pd.read_csv('laptops.csv')
df

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
0,ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...,New,Asus,ExpertBook,Intel Core i5,8,512,SSD,NaN,15.6,No,1009.00
1,Alurin Go Start Intel Celeron N4020/8GB/256GB ...,New,Alurin,Go,Intel Celeron,8,256,SSD,NaN,15.6,No,299.00
2,ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...,New,Asus,ExpertBook,Intel Core i3,8,256,SSD,NaN,15.6,No,789.00
3,MSI Katana GF66 12UC-082XES Intel Core i7-1270...,New,MSI,Katana,Intel Core i7,16,1000,SSD,RTX 3050,15.6,No,1199.00
4,HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...,New,HP,15S,Intel Core i5,16,512,SSD,NaN,15.6,No,669.01
...,...,...,...,...,...,...,...,...,...,...,...,...
2155,Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...,Refurbished,Razer,Blade,Intel Core i7,16,1000,SSD,RTX 3060,17.3,No,2699.99
2156,Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...,Refurbished,Razer,Blade,Intel Core i7,16,1000,SSD,RTX 3070,17.3,No,2899.99
2157,Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...,Refurbished,Razer,Blade,Intel Core i7,32,1000,SSD,RTX 3080,17.3,No,3399.99
2158,Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...,Refurbished,Razer,Book,Intel Evo Core i7,16,1000,SSD,NaN,13.4,Yes,1899.99
2159,Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...,Refurbished,Razer,Book,Intel Evo Core i7,16,256,SSD,NaN,13.4,Yes,1699.99

In [4]:
df.shape

(2160, 12)

In [5]:
df.dtypes

Laptop           object
Status           object
Brand            object
Model            object
CPU              object
RAM               int64
Storage           int64
Storage type     object
GPU              object
Screen          float64
Touch            object
Final Price     float64
dtype: object

In [6]:
df.columns

Index(['Laptop', 'Status', 'Brand', 'Model', 'CPU', 'RAM', 'Storage',
       'Storage type', 'GPU', 'Screen', 'Touch', 'Final Price'],
      dtype='object')

In [7]:
df.values

array([['ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core i5-1235U/8GB/512GB SSD/15.6"',
        'New', 'Asus', ..., 15.6, 'No', 1009.0],
       ['Alurin Go Start Intel Celeron N4020/8GB/256GB SSD/15.6"', 'New',
        'Alurin', ..., 15.6, 'No', 299.0],
       ['ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core i3-1215U/8GB/256GB SSD/15.6"',
        'New', 'Asus', ..., 15.6, 'No', 789.0],
       ...,
       ['Razer Blade 17 FHD 360Hz Intel Core i7-11800H/32GB/1TB SSD/RTX 3080/17.3"',
        'Refurbished', 'Razer', ..., 17.3, 'No', 3399.99],
       ['Razer Book 13 Intel Evo Core i7-1165G7/16GB/1TB SSD/13.4" Táctil',
        'Refurbished', 'Razer', ..., 13.4, 'Yes', 1899.99],
       ['Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/256GB SSD/13.4" Táctil',
        'Refurbished', 'Razer', ..., 13.4, 'Yes', 1699.99]], dtype=object)

In [8]:
# start 5 rows
df.head()

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
0,ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...,New,Asus,ExpertBook,Intel Core i5,8,512,SSD,NaN,15.6,No,1009.00
1,Alurin Go Start Intel Celeron N4020/8GB/256GB ...,New,Alurin,Go,Intel Celeron,8,256,SSD,NaN,15.6,No,299.00
2,ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...,New,Asus,ExpertBook,Intel Core i3,8,256,SSD,NaN,15.6,No,789.00
3,MSI Katana GF66 12UC-082XES Intel Core i7-1270...,New,MSI,Katana,Intel Core i7,16,1000,SSD,RTX 3050,15.6,No,1199.00
4,HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...,New,HP,15S,Intel Core i5,16,512,SSD,NaN,15.6,No,669.01

In [9]:
# end 5 rows
df.tail()

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
2155,Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...,Refurbished,Razer,Blade,Intel Core i7,16,1000,SSD,RTX 3060,17.3,No,2699.99
2156,Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...,Refurbished,Razer,Blade,Intel Core i7,16,1000,SSD,RTX 3070,17.3,No,2899.99
2157,Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...,Refurbished,Razer,Blade,Intel Core i7,32,1000,SSD,RTX 3080,17.3,No,3399.99
2158,Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...,Refurbished,Razer,Book,Intel Evo Core i7,16,1000,SSD,NaN,13.4,Yes,1899.99
2159,Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...,Refurbished,Razer,Book,Intel Evo Core i7,16,256,SSD,NaN,13.4,Yes,1699.99

In [10]:
# random 5 rows
df.sample(5)

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
1299,Acer TravelMate TMP215-52 Intel Core i3-10110U...,New,Acer,TravelMate,Intel Core i3,8,256,SSD,NaN,15.6,No,547.19
1883,HP 250 G8 Intel Core i3-1115G4/8GB/512GB SSD/1...,Refurbished,HP,250,Intel Core i3,8,512,SSD,NaN,15.6,No,392.69
260,ASUS ROG Strix G16 G614JZ-N3008 Intel Core i7-...,New,Asus,ROG,Intel Core i7,32,1000,NaN,RTX 4080,16.0,No,2599.01
359,MSI Katana GF66 12UC-820XES Intel Core i7-1265...,New,MSI,Katana,Intel Core i7,16,512,SSD,RTX 3050,15.6,No,1199.00
1949,Lenovo IdeaPad S145-15IIL Intel Core i7-1065G7...,Refurbished,Lenovo,IdeaPad,Intel Core i7,8,256,SSD,NaN,15.6,No,501.99

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Laptop        2160 non-null   object
 1   Status        2160 non-null   object
 2   Brand         2160 non-null   object
 3   Model         2160 non-null   object
 4   CPU           2160 non-null   object
 5   RAM           2160 non-null   int64
 6   Storage       2160 non-null   int64
 7   Storage type  2118 non-null   object
 8   GPU           789 non-null    object
 9   Screen        2156 non-null   float64
 10  Touch         2160 non-null   object
 11  Final Price   2160 non-null   float64
dtypes: float64(2), int64(2), object(8)
memory usage: 202.6+ KB

In [12]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [13]:
df.describe()

               RAM      Storage       Screen  Final Price
count  2160.000000  2160.000000  2156.000000  2160.000000
mean     15.413889   596.294444    15.168112  1312.638509
std       9.867815   361.220506     1.203329   911.475417
min       4.000000     0.000000    10.100000   201.050000
25%       8.000000   256.000000    14.000000   661.082500
50%      16.000000   512.000000    15.600000  1031.945000
75%      16.000000  1000.000000    15.600000  1708.970000
max     128.000000  4000.000000    18.000000  7150.470000

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
0,ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...,New,Asus,ExpertBook,Intel Core i5,8,512,SSD,NaN,15.6,No,1009.00
1,Alurin Go Start Intel Celeron N4020/8GB/256GB ...,New,Alurin,Go,Intel Celeron,8,256,SSD,NaN,15.6,No,299.00
2,ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...,New,Asus,ExpertBook,Intel Core i3,8,256,SSD,NaN,15.6,No,789.00
3,MSI Katana GF66 12UC-082XES Intel Core i7-1270...,New,MSI,Katana,Intel Core i7,16,1000,SSD,RTX 3050,15.6,No,1199.00
4,HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...,New,HP,15S,Intel Core i5,16,512,SSD,NaN,15.6,No,669.01
...,...,...,...,...,...,...,...,...,...,...,...,...
2155,Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...,Refurbished,Razer,Blade,Intel Core i7,16,1000,SSD,RTX 3060,17.3,No,2699.99
2156,Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...,Refurbished,Razer,Blade,Intel Core i7,16,1000,SSD,RTX 3070,17.3,No,2899.99
2157,Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...,Refurbished,Razer,Blade,Intel Core i7,32,1000,SSD,RTX 3080,17.3,No,3399.99
2158,Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...,Refurbished,Razer,Book,Intel Evo Core i7,16,1000,SSD,NaN,13.4,Yes,1899.99
2159,Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...,Refurbished,Razer,Book,Intel Evo Core i7,16,256,SSD,NaN,13.4,Yes,1699.99

In [16]:
df['Brand']

0         Asus
1       Alurin
2         Asus
3          MSI
4           HP
         ...
2155     Razer
2156     Razer
2157     Razer
2158     Razer
2159     Razer
Name: Brand, Length: 2160, dtype: object

In [17]:
df.loc[0, 'Brand'] = 'HP'

In [18]:
hp_laptops = df[df['Brand'] == 'HP']
hp_laptops

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
0,ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...,New,HP,ExpertBook,Intel Core i5,8,512,SSD,NaN,15.6,No,1009.00
4,HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...,New,HP,15S,Intel Core i5,16,512,SSD,NaN,15.6,No,669.01
9,HP Victus 16-d1038ns Intel Core i7-12700H/16GB...,New,HP,Victus,Intel Core i7,16,512,SSD,RTX 3050,16.1,No,1149.00
15,HP 15S-FQ5013NS Intel Core i5-1235U/8GB/512GB ...,New,HP,15S,Intel Core i5,8,512,SSD,NaN,15.6,No,699.00
17,HP 15S-FQ2163NS Intel Core i3-1115G4/8GB/512GB...,New,HP,15S,Intel Core i3,8,512,SSD,NaN,15.6,No,549.00
...,...,...,...,...,...,...,...,...,...,...,...,...
1921,HP Victus 16-e0030ns AMD Ryzen 5 5600H/16GB/51...,Refurbished,HP,Victus,AMD Ryzen 5,16,512,SSD,RTX 3050,16.1,No,735.84
1922,HP ZBook Firefly 14 G8 Intel Core i7-1165G7/16...,Refurbished,HP,Zbook,Intel Core i7,16,512,SSD,NaN,14.0,No,1619.46
1923,HP ZBook Firefly 15 G8 Intel Core i7-1165G7/16...,Refurbished,HP,Zbook,Intel Core i7,16,512,SSD,T 500,15.6,No,2677.83
1924,HP ZBook Fury G8 Intel Core i7-11800H/16 GB/51...,Refurbished,HP,Zbook,Intel Core i7,16,512,SSD,RTX A3000,15.6,No,3848.01
1925,HP ZBook Fury G8 Intel Core i9-11900H/32GB/1TB...,Refurbished,HP,Zbook,Intel Core i9,32,1000,SSD,NaN,15.6,No,4805.65

In [21]:
df.rename(columns={'Brand': 'Brands'}, inplace=True)

In [22]:
df.iloc[55]

Laptop          HP Victus 16-e0101ns AMD Ryzen 7 5800H/16GB/51...
Status                                                        New
Brands                                                         HP
Model                                                      Victus
CPU                                                   AMD Ryzen 7
RAM                                                            16
Storage                                                       512
Storage type                                                  SSD
GPU                                                      RTX 3060
Screen                                                       16.1
Touch                                                          No
Final Price                                               1299.01
Name: 55, dtype: object

In [23]:
df[0:3]

,Laptop,Status,Brands,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
0,ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...,New,HP,ExpertBook,Intel Core i5,8,512,SSD,NaN,15.6,No,1009.0
1,Alurin Go Start Intel Celeron N4020/8GB/256GB ...,New,Alurin,Go,Intel Celeron,8,256,SSD,NaN,15.6,No,299.0
2,ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...,New,Asus,ExpertBook,Intel Core i3,8,256,SSD,NaN,15.6,No,789.0

In [25]:
df[2:15:3]

,Laptop,Status,Brands,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
2,ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...,New,Asus,ExpertBook,Intel Core i3,8,256,SSD,NaN,15.6,No,789.0
5,MSI Crosshair 17 C12VF-264XES Intel Core i7-12...,New,MSI,Crosshair,Intel Core i7,32,1000,SSD,RTX 4060,17.3,No,1699.0
8,Medion Akoya E15415 Intel Core i5-10210U/8GB/2...,New,Medion,Akoya,Intel Core i5,8,256,SSD,NaN,15.6,No,519.0
11,MSI Thin GF63 12VE-021XES Intel Core i7-12650H...,New,MSI,Thin,Intel Core i7,16,1000,SSD,RTX 4050,15.6,No,1399.0
14,Lenovo IdeaPad 1 15ADA7 AMD Ryzen 3 3250U/8GB/...,New,Lenovo,IdeaPad,AMD Ryzen 3,8,256,SSD,NaN,15.6,No,391.0